## 3.1 初始N维数组对象


In [5]:
import numpy as np
print(np.__version__)

1.19.2


### 示例 3.1

In [7]:
array_1x6 = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=np.float64)
print(array_1x6)
print(array_1x6.ndim)
print(array_1x6.shape)
print(array_1x6.dtype)

[1. 2. 3. 4. 5. 6.]
1
(6,)
float64


### 示例 3.2

In [8]:
array_2x6 = np.array([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0], [1.1, 2.1, 3.1, 4.1, 5.1, 6.1]])
print(array_2x6)
print(array_2x6.ndim)
print(array_2x6.shape)
print(array_2x6.dtype)

[[1.  2.  3.  4.  5.  6. ]
 [1.1 2.1 3.1 4.1 5.1 6.1]]
2
(2, 6)
float64


### 示例 3.3

In [9]:
array_2x3x6 = np.array([[[1.0, 2.0, 3.0, 4.0, 5.0, 6.0],[1.1, 2.1, 3.1, 4.1, 5.1, 6.1],[1.2, 2.2, 3.2, 4.2, 5.2, 6.2]],
                        [[7.0, 8.0, 9.0, 10.0, 11.0, 12.0],[7.1, 8.1, 9.1, 10.1, 11.1, 12.1],[7.2, 8.2, 9.2, 10.2, 11.2, 12.2]]])
print(array_2x3x6)
print(array_2x3x6.ndim)
print(array_2x3x6.shape)
print(array_2x3x6.dtype)

[[[ 1.   2.   3.   4.   5.   6. ]
  [ 1.1  2.1  3.1  4.1  5.1  6.1]
  [ 1.2  2.2  3.2  4.2  5.2  6.2]]

 [[ 7.   8.   9.  10.  11.  12. ]
  [ 7.1  8.1  9.1 10.1 11.1 12.1]
  [ 7.2  8.2  9.2 10.2 11.2 12.2]]]
3
(2, 3, 6)
float64
